/**
 * Emit a full design-model.yaml: the measured brand dimensions (color,
 * typography, spacing, radii, shadows) plus the motion block. The motion section
 * is produced by the same spliceMotion path used for standalone emission, so it
 * stays byte-identical and passes the motion validator unchanged.
 *
 * The shape is Hue-adjacent (a `colors.<mode>` palette, a `typography` block,
 * `spacing`/`radii` scales, and `motion:`), readable on its own and easy to map
 * onto Hue's primitives/tokens nesting.
 */

import { Document, isSeq } from 'yaml';
import type { MotionModel } from '../analyze/model.js';
import type { BrandModel, TypographyRole, FontFaceRule } from '../brand/types.js';
import { spliceMotion } from './motion-yaml.js';

export interface DesignModel {
  name: string;
  source: string;
  capturedAt: string;
  brand: BrandModel;
  motion: MotionModel;
}

const HEADER = [
  ' Generated by understudy. Measured brand identity, not guessed.',
  ' Colors, type, spacing, and motion are read from the live, rendered page.',
  ' confidence.brand and motion.meta.confidence report real uncertainty.',
].join('\n');

export function emitDesignModel(design: DesignModel): string {
  const { brand } = design;
  const doc = new Document({});
  doc.commentBefore = HEADER;

  const brandBlock: Record<string, unknown> = {
    name: design.name,
    source: design.source,
    captured_at: design.capturedAt,
    primary_mode: brand.mode,
    confidence: { brand: brand.confidence, motion: design.motion.meta.confidence },
    colors: brand.colors,
    ...(brand.accents.length > 0 ? { accents: brand.accents } : {}),
    ...(Object.keys(brand.states).length > 0 ? { states: brand.states } : {}),
    ...(brand.accentHover ? { accent_hover: brand.accentHover } : {}),
    typography: {
      families: brand.typography.families,
      scale: brand.typography.scale,
      ...(brand.typography.scaleRatio ? { scale_ratio: brand.typography.scaleRatio } : {}),
      ...(brand.typography.responsive ? { responsive: brand.typography.responsive } : {}),
      weights: brand.typography.weights,
      display: role(brand.typography.display),
      body: role(brand.typography.body),
      ...(brand.typography.mono ? { mono: role(brand.typography.mono) } : {}),
      ...(brand.typography.fontFaces.length > 0 ? { fonts: brand.typography.fontFaces.map(fontFace) } : {}),
      ...(brand.typography.fontFiles && brand.typography.fontFiles.length > 0
        ? { font_files: brand.typography.fontFiles }
        : {}),
    },
    spacing: brand.spacing,
    radii: brand.radii,
    ...(brand.borderWidths.length > 0 ? { border_widths: brand.borderWidths } : {}),
    ...(brand.containers.length > 0 ? { containers: brand.containers } : {}),
    ...(brand.shadows.length > 0 ? { shadows: brand.shadows } : {}),
    ...(brand.gradients.length > 0 ? { gradients: brand.gradients } : {}),
    ...(brand.logo ? { logo: brand.logo } : {}),
    ...(Object.values(brand.accessibility).some((a) => a && a.length > 0) ? { accessibility: brand.accessibility } : {}),
    ...(Object.keys(brand.provenance).length > 0 ? { provenance: brand.provenance } : {}),
    observed: { sampled_elements: brand.sampled, ...(brand.challenged ? { challenge_page: true } : {}) },
  };

  doc.contents = doc.createNode(brandBlock);
  styleBrandArrays(doc);
  spliceMotion(doc, design.motion); // appends and styles the motion block

  return doc.toString({ lineWidth: 0 });
}

function role(r: TypographyRole): Record<string, unknown> {
  return {
    family: r.family,
    size: `${r.size}px`,
    weight: r.weight,
    line_height: r.lineHeight > 0 ? r.lineHeight : 'normal',
    letter_spacing: r.letterSpacing,
  };
}

function fontFace(f: FontFaceRule): Record<string, unknown> {
  const out: Record<string, unknown> = { family: f.family, weight: f.weight, style: f.style };
  if (f.src) out.src = f.src;
  return out;
}

/** Render the numeric/string scales inline for readability. */
function styleBrandArrays(doc: Document): void {
  const paths = [
    ['spacing'], ['radii'], ['border_widths'], ['containers'], ['accents'],
    ['typography', 'scale'], ['typography', 'weights'], ['typography', 'families'],
  ];
  for (const path of paths) {
    const node = doc.getIn(path, true);
    if (isSeq(node)) node.flow = true;
  }
}

/** Derive a brand name from the source URL host (best effort). */
export function nameFromUrl(url: string): string {
  try {
    const host = new URL(url).hostname.replace(/^www\./, '');
    const label = host.split('.')[0] || host;
    return label.charAt(0).toUpperCase() + label.slice(1);
  } catch {
    return 'Captured Brand';
  }
}
