/**
 * Emit the §5 `motion` block as YAML.
 *
 * Provenance shorthand (§5): when a token's provenance is `measured` we emit the
 * scalar/array shorthand (`base: 240`, `standard: [0.32, 0.72, 0, 1]`); any other
 * provenance emits the long form with an explicit `provenance:` line. The parser
 * (and validator) accept both. This is what keeps the v0.3 rationale work additive.
 *
 * This module makes no assumption that Hue is the only consumer (§2): it produces
 * a standalone `motion:` document that also splices cleanly (see merge.ts).
 */

import { Document, isSeq, isMap } from 'yaml';
import type {
  MotionModel,
  EasingToken,
  DurationToken,
  StaggerToken,
  SemanticEntry,
} from '../analyze/model.js';

const HEADER = [
  ' Generated by understudy. Measured motion, not guessed.',
  ' meta.confidence reports real uncertainty; treat it as authoritative.',
  ' Values with provenance "measured" use scalar shorthand; the parser accepts both forms.',
].join('\n');

/** Build the plain-object motion block with provenance shorthand applied. */
export function buildMotionBlock(model: MotionModel): Record<string, unknown> {
  return {
    meta: {
      source: model.meta.source,
      captured_at: model.meta.capturedAt,
      confidence: model.meta.confidence,
      passes: model.meta.passes,
    },
    primitives: {
      duration: mapValues(model.primitives.duration, emitDuration),
      easing: mapValues(model.primitives.easing, emitEasing),
      stagger: mapValues(model.primitives.stagger, emitStagger),
    },
    semantic: mapValues(model.semantic, emitSemantic),
    choreography: model.choreography.map((c) => ({
      name: c.name,
      trigger: c.trigger,
      steps: c.steps.map((s) => ({ target: s.target, delay: s.delay, token: s.token })),
    })),
    personality: {
      archetype: model.personality.archetype,
      evidence: model.personality.evidence,
    },
    observed: {
      samples: model.observed.samples,
      rejected: model.observed.rejected,
      notes: model.observed.notes,
    },
  };
}

/** Emit a full standalone `motion:` YAML document. */
export function emitMotionYaml(model: MotionModel): string {
  const doc = new Document({});
  doc.commentBefore = HEADER;
  spliceMotion(doc, model);
  return doc.toString({ lineWidth: 0 });
}

/**
 * Set (or replace) the top-level `motion:` key on an existing document, styled
 * to match the contract. Shared by standalone emission and merge.ts so both
 * produce byte-identical motion nodes.
 */
export function spliceMotion(doc: Document, model: MotionModel): void {
  // createNode deeply converts the plain object into YAML nodes; a bare set()
  // would store raw JS values that the flow styling below cannot see.
  doc.set('motion', doc.createNode(buildMotionBlock(model)));
  styleMotionNode(doc);
}

function emitDuration(token: DurationToken): unknown {
  return token.provenance === 'measured' ? token.value : { value: token.value, provenance: token.provenance };
}

function emitStagger(token: StaggerToken): unknown {
  return token.provenance === 'measured' ? token.value : { value: token.value, provenance: token.provenance };
}

function emitEasing(token: EasingToken): unknown {
  if (token.kind === 'spring') {
    const base = { stiffness: token.stiffness, damping: token.damping, mass: token.mass };
    return token.provenance === 'measured' ? base : { ...base, provenance: token.provenance };
  }
  return token.provenance === 'measured'
    ? [...token.control]
    : { value: [...token.control], provenance: token.provenance };
}

function emitSemantic(entry: SemanticEntry): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (entry.duration !== undefined) out.duration = entry.duration;
  if (entry.easing !== undefined) out.easing = entry.easing;
  if (entry.stagger !== undefined) out.stagger = entry.stagger;
  if (entry.coupling !== undefined) out.coupling = entry.coupling;
  if (entry.ratio !== undefined) out.ratio = entry.ratio;
  return out;
}

/**
 * Cosmetic flow styling so the output matches the contract's shape: easing
 * control arrays, semantic entries, choreography steps, and meta.passes render
 * inline; spring maps and evidence lists stay in block form. Purely visual;
 * structure and validity do not depend on it.
 */
function styleMotionNode(doc: Document): void {
  const passes = doc.getIn(['motion', 'meta', 'passes'], true);
  if (isSeq(passes)) passes.flow = true;

  const easing = doc.getIn(['motion', 'primitives', 'easing'], true);
  if (isMap(easing)) {
    for (const item of easing.items) {
      if (isSeq(item.value)) item.value.flow = true; // bezier control array
    }
  }

  const semantic = doc.getIn(['motion', 'semantic'], true);
  if (isMap(semantic)) {
    for (const item of semantic.items) {
      if (isMap(item.value)) item.value.flow = true;
    }
  }

  const choreography = doc.getIn(['motion', 'choreography'], true);
  if (isSeq(choreography)) {
    for (const entry of choreography.items) {
      if (!isMap(entry)) continue;
      const steps = entry.get('steps', true);
      if (isSeq(steps)) {
        for (const step of steps.items) {
          if (isMap(step)) step.flow = true;
        }
      }
    }
  }
}

function mapValues<T>(obj: Record<string, T>, fn: (v: T) => unknown): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = fn(v);
  return out;
}
