/**
 * Consumable token export: turn the measured design model into paste-ready
 * output, not just a descriptive YAML. Three formats:
 *   - CSS custom properties for the whole brand + motion (per color mode);
 *   - a Tailwind `theme.extend` config;
 *   - W3C Design Tokens (DTCG) JSON, for Style Dictionary / Figma Tokens / etc.
 */

import type { DesignModel } from './design-model.js';
import type { ColorTokens, Mode } from '../brand/types.js';
import type { MotionModel } from '../analyze/model.js';
import { toThemeVars } from './tokens-css.js';

// --------------------------------------------------------------------------
// CSS custom properties
// --------------------------------------------------------------------------

export function toBrandCss(design: DesignModel): string {
  const { brand, motion } = design;
  const primary = brand.colors[brand.mode];
  const root: string[] = [];

  if (primary) root.push(...colorLines(primary));
  brand.accents.forEach((a, i) => root.push(`  --color-accent-${i + 1}: ${a};`));
  for (const [state, hex] of Object.entries(brand.states)) root.push(`  --color-${state}: ${hex};`);

  root.push(`  --font-display: ${cssFamily(brand.typography.display.family)};`);
  root.push(`  --font-body: ${cssFamily(brand.typography.body.family)};`);
  if (brand.typography.mono) root.push(`  --font-mono: ${cssFamily(brand.typography.mono.family, 'monospace')};`);
  brand.typography.scale.forEach((s, i) => root.push(`  --text-${i}: ${s}px;`));

  brand.spacing.forEach((s, i) => root.push(`  --space-${i}: ${s}px;`));
  brand.radii.forEach((r, i) => root.push(`  --radius-${i}: ${r}px;`));
  brand.shadows.forEach((sh, i) => root.push(`  --shadow-${i}: ${sh};`));
  for (const [k, v] of Object.entries(toThemeVars(motion))) root.push(`  --${k}: ${v};`);

  const out = [`/* Generated by understudy from ${design.source}. Brand + motion tokens. */`, ':root {', ...root, '}'];

  const other: Mode = brand.mode === 'light' ? 'dark' : 'light';
  const otherColors = brand.colors[other];
  if (otherColors) {
    const lines = colorLines(otherColors);
    out.push(`@media (prefers-color-scheme: ${other}) {`, '  :root {', ...lines.map((l) => `  ${l}`), '  }', '}');
    out.push(`[data-theme="${other}"] {`, ...lines, '}');
  }
  return out.join('\n') + '\n';
}

function colorLines(c: ColorTokens): string[] {
  return [
    `  --color-background: ${c.background};`,
    `  --color-surface: ${c.surface};`,
    `  --color-text-1: ${c.text1};`,
    `  --color-text-2: ${c.text2};`,
    `  --color-accent: ${c.accent};`,
    `  --color-border: ${c.border};`,
  ];
}

function cssFamily(family: string, fallback = 'sans-serif'): string {
  const quoted = /\s/.test(family) ? `"${family}"` : family;
  return `${quoted}, ${fallback}`;
}

// --------------------------------------------------------------------------
// Tailwind theme.extend
// --------------------------------------------------------------------------

export function toTailwindConfig(design: DesignModel): string {
  const { brand, motion } = design;
  const primary = brand.colors[brand.mode];

  const colors: Record<string, string> = {};
  if (primary) {
    Object.assign(colors, {
      background: primary.background, surface: primary.surface,
      'text-1': primary.text1, 'text-2': primary.text2, accent: primary.accent, border: primary.border,
    });
  }
  brand.accents.forEach((a, i) => (colors[`accent-${i + 1}`] = a));
  Object.assign(colors, brand.states);

  const fontFamily: Record<string, string[]> = {
    display: [brand.typography.display.family, 'sans-serif'],
    body: [brand.typography.body.family, 'sans-serif'],
  };
  if (brand.typography.mono) fontFamily.mono = [brand.typography.mono.family, 'monospace'];

  const config = {
    theme: {
      extend: {
        colors,
        fontFamily,
        fontSize: { display: `${brand.typography.display.size}px`, body: `${brand.typography.body.size}px` },
        spacing: pxMap(brand.spacing),
        borderRadius: pxMap(brand.radii),
        boxShadow: Object.fromEntries(brand.shadows.map((s, i) => [String(i), s])),
        transitionDuration: durationMap(motion),
        transitionTimingFunction: easingMap(motion),
      },
    },
  };
  return `/** tailwind.config generated by understudy from ${design.source} */\nexport default ${JSON.stringify(config, null, 2)};\n`;
}

function pxMap(values: number[]): Record<string, string> {
  return Object.fromEntries(values.map((v, i) => [String(i), `${v}px`]));
}

function durationMap(motion: MotionModel): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, token] of Object.entries(motion.primitives.duration)) out[name] = `${token.value}ms`;
  return out;
}

function easingMap(motion: MotionModel): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, token] of Object.entries(motion.primitives.easing)) {
    if (token.kind === 'bezier') out[name] = `cubic-bezier(${token.control.join(', ')})`;
  }
  return out;
}

// --------------------------------------------------------------------------
// W3C Design Tokens (DTCG)
// --------------------------------------------------------------------------

export function toDesignTokens(design: DesignModel): Record<string, unknown> {
  const { brand, motion } = design;
  const primary = brand.colors[brand.mode];
  const color: Record<string, unknown> = {};
  if (primary) {
    for (const [role, hex] of Object.entries(primary)) color[role] = { $value: hex, $type: 'color' };
  }
  brand.accents.forEach((a, i) => (color[`accent-${i + 1}`] = { $value: a, $type: 'color' }));
  for (const [state, hex] of Object.entries(brand.states)) color[state] = { $value: hex, $type: 'color' };

  const fontFamily: Record<string, unknown> = {
    display: { $value: brand.typography.display.family, $type: 'fontFamily' },
    body: { $value: brand.typography.body.family, $type: 'fontFamily' },
  };
  if (brand.typography.mono) fontFamily.mono = { $value: brand.typography.mono.family, $type: 'fontFamily' };

  const duration: Record<string, unknown> = {};
  for (const [name, token] of Object.entries(motion.primitives.duration)) {
    duration[name] = { $value: `${token.value}ms`, $type: 'duration' };
  }
  const cubicBezier: Record<string, unknown> = {};
  for (const [name, token] of Object.entries(motion.primitives.easing)) {
    if (token.kind === 'bezier') cubicBezier[name] = { $value: token.control, $type: 'cubicBezier' };
  }

  return {
    $description: `Generated by understudy from ${design.source}`,
    color,
    fontFamily,
    fontSize: dimensionGroup(brand.typography.scale),
    spacing: dimensionGroup(brand.spacing),
    borderRadius: dimensionGroup(brand.radii),
    shadow: Object.fromEntries(brand.shadows.map((s, i) => [String(i), { $value: s, $type: 'shadow' }])),
    duration,
    cubicBezier,
  };
}

function dimensionGroup(values: number[]): Record<string, unknown> {
  return Object.fromEntries(values.map((v, i) => [String(i), { $value: `${v}px`, $type: 'dimension' }]));
}
